### ISSUE TITLE
ボールを発射する

### ISSUE THREAD

**Issue by Hirose-Yuto** [WilKen3/RobotCodeTest1#2]
アームを上げて、ボールを発射することができるようにする。
そのとき、ボールが真っ直ぐ飛ぶように左右のモータの速さを揃えること。

**Comment by WilKen3** [comment]
ボールの取り込みとついでにやってあります。

**Comment by Hirose-Yuto** [comment]
[`configSelectedFeedbackSensor()`](https://store.ctr-electronics.com/content/api/java/html/classcom_1_1ctre_1_1phoenix_1_1motorcontrol_1_1can_1_1_talon_s_r_x.html#af2ef6fdd84542e78b1265baef5ddf328)でセンサーの設定をして、
[`getSelectedSensorVelocity()`](https://store.ctr-electronics.com/content/api/java/html/interfacecom_1_1ctre_1_1phoenix_1_1motorcontrol_1_1_i_motor_controller.html#a2e40db44cfbd62192ffac3fb7ccf5166)でシューターの速さを取得できる。

ちなみに付属のセンサーはMagEncoderで手法はrelativeでいいよ

**Comment by WilKen3** [comment]
多分できた
