### ISSUE TITLE
ドライブベースに関するものをDriveクラスにまとめる

### ISSUE THREAD

**Issue by Hirose-Yuto** [WilKen3/RobotCodeTest1#4]
Drive.javaを作成、`Drive` classを作る。
`Drive`クラスは、ドライブベースに関するもの、つまり、
`driveLeftFrontMotor`などのモータや、それらをまとめた`DifferentialDrive`クラスの`drive`などをフィールドとして持ち、
ドライブベースを動かすメソッドを持つ。

**Comment by WilKen3** [comment]
終わりました
