### ISSUE TITLE
シューターに関するものをShooterにまとめる

### ISSUE THREAD

**Issue by Hirose-Yuto** [WilKen3/RobotCodeTest1#5]
Shooter.javaを作成、`Shooter` classを作る。
`Shooter`クラスは、シューターに関するもの、つまり、
`intakeMotor`や`leftShooter`、`intakeBelt`などをフィールドとして持ち、
ボールの回収、排出、発射などを行うメソッドを持つ。

**Comment by WilKen3** [comment]
終わりました
