### ISSUE TITLE
Stateの導入を行う

### ISSUE THREAD

**Issue by Hirose-Yuto** [WilKen3/RobotCodeTest1#6]
`State` classを用いたロボットの制御を行う。

Stateの概念は難しいので神の解説を聞いてくださいな。

ちなみにこれは大改造が必要になるので結構大変。

**Comment by Hirose-Yuto** [comment]
https://github.com/sakura-tempesta-6909/RobotCode-2022.git
これに則った感じで

**Comment by WilKen3** [comment]
Introstateてマージした方がいいですよね？
