### ISSUE TITLE
ボールを上手く取り込む

### ISSUE THREAD

**Issue by Hirose-Yuto** [WilKen3/RobotCodeTest1#9]
# やりたいこと
今のままだとボールを回収するとき前後のベルトを一緒回してるけど、これだとボールを均等に回収できない。
 (どんどん奥にボールが追いやられて変に詰まっちゃう)

だから、前のセンサーでボールを検知するまで後ろのベルトは回さず、センサーで検知したらベルトを回したい。
そして、前のセンサーからボールが消えたらベルトの動きを止めたい(ボールを奥に持って行きすぎないため)

後ろのセンサーは単純で、一番後ろまでボールが来たらベルトを回したくないから、ボールを検知したらベルトを回さないようにする。(同じことの繰り返しだけど)

ちなみに、前のセンサは2つのベルトの間にある。

# 基本情報
`DigitalInput`クラスのセンサーがアームの前後についてて、前ののポートが0番、後ろのが1番。

なんのセンサーかというと、ボールが入ったかどうかを検知するためのもの。
`DigitalInput` には、`get()` メソッドが定義されてて、ボールが検知されたときに `false` 、ボールが無いときに`true`になる。

メソッドの詳しい情報はPhoenixのドキュメントを参照。

**Comment by WilKen3** [comment]
終わりました
